services:
  mysql:
    image: mysql
    container_name: mysql_todolistExamen
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    volumes:
      - mysql_todolistExamen:/var/lib/mysql

  todolistExamen:
    image: todolistexamen:latest
    container_name: todolistExamen
    ports:
      - "3000:3000"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_todolistExamen: